# Generated by Django 5.2.18 on 2026-10-07 07:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("owner_session", models.CharField(db_index=True, max_length=40)),
                ("original_name", models.CharField(max_length=255)),
                ("storage_name", models.CharField(max_length=255, unique=True)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("row_count", models.PositiveIntegerField()),
                ("columns", models.JSONField()),
                ("preview", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
